openapi: 3.1.0
info:
  description: "Note: You need to get an access token using the `/auth/{id}` endpoint\
    \ first to call any API endpoints under `/api`."
  title: Youtube Music API Server
  version: 1.0.0
servers:
- url: /
security:
- bearerAuth: []
paths:
  /api/v1/previous:
    post:
      description: Plays the previous song in the queue
      responses:
        "204":
          description: Success
      summary: play previous song
  /api/v1/next:
    post:
      description: Plays the next song in the queue
      responses:
        "204":
          description: Success
      summary: play next song
  /api/v1/play:
    post:
      description: Change the state of the player to play
      responses:
        "204":
          description: Success
      summary: Play
  /api/v1/pause:
    post:
      description: Change the state of the player to pause
      responses:
        "204":
          description: Success
      summary: Pause
  /api/v1/toggle-play:
    post:
      description: "Change the state of the player to play if paused, or pause if\
        \ playing"
      responses:
        "204":
          description: Success
      summary: Toggle play/pause
  /api/v1/like-state:
    get:
      description: Get the current like state
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_api_v1_like_state_get_200_response"
          description: Success
      summary: get like state
  /api/v1/like:
    post:
      description: Set the current song as liked
      responses:
        "204":
          description: Success
      summary: like song
  /api/v1/dislike:
    post:
      description: Set the current song as disliked
      responses:
        "204":
          description: Success
      summary: dislike song
  /api/v1/seek-to:
    post:
      description: Seek to a specific time in the current song
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_seek_to_post_request"
        description: seconds to seek to
      responses:
        "204":
          description: Success
      summary: seek
  /api/v1/go-back:
    post:
      description: Move the current song back by a number of seconds
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_seek_to_post_request"
        description: seconds to go back
      responses:
        "204":
          description: Success
      summary: go back
  /api/v1/go-forward:
    post:
      description: Move the current song forward by a number of seconds
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_seek_to_post_request"
        description: seconds to go forward
      responses:
        "204":
          description: Success
      summary: go forward
  /api/v1/shuffle:
    get:
      description: Get the current shuffle state
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_api_v1_shuffle_get_200_response"
          description: Success
      summary: get shuffle state
    post:
      description: Shuffle the queue
      responses:
        "204":
          description: Success
      summary: shuffle
  /api/v1/repeat-mode:
    get:
      description: "Get the current repeat mode (NONE, ALL, ONE)"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_api_v1_repeat_mode_get_200_response"
          description: Success
      summary: get current repeat mode
  /api/v1/switch-repeat:
    post:
      description: Switch the repeat mode
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_switch_repeat_post_request"
        description: number of times to click the repeat button
      responses:
        "204":
          description: Success
      summary: switch repeat
  /api/v1/volume:
    get:
      description: Get the current volume state of the player
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_api_v1_volume_get_200_response"
          description: Success
      summary: get volume state
    post:
      description: Set the volume of the player
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_volume_post_request"
        description: volume to set
      responses:
        "204":
          description: Success
      summary: set volume
  /api/v1/fullscreen:
    get:
      description: Get the current fullscreen state
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_api_v1_fullscreen_get_200_response"
          description: Success
      summary: get fullscreen state
    post:
      description: Set the fullscreen state of the player
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_fullscreen_get_200_response"
        description: fullscreen state
      responses:
        "204":
          description: Success
      summary: set fullscreen
  /api/v1/toggle-mute:
    post:
      description: Toggle the mute state of the player
      responses:
        "204":
          description: Success
      summary: toggle mute
  /api/v1/song-info:
    get:
      deprecated: true
      description: Get the current song info
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_api_v1_song_info_get_200_response"
          description: Success
        "204":
          description: No song info
      summary: get current song info
  /api/v1/song:
    get:
      description: Get the current song info
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_api_v1_song_info_get_200_response"
          description: Success
        "204":
          description: No song info
      summary: get current song info
  /api/v1/queue-info:
    get:
      deprecated: true
      description: Get the current queue info
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
        "204":
          description: No queue info
      summary: get current queue info
  /api/v1/queue:
    delete:
      description: Clear the queue
      responses:
        "204":
          description: Success
      summary: clear queue
    get:
      description: Get the current queue info
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
        "204":
          description: No queue info
      summary: get current queue info
    patch:
      description: Set the current index of the queue
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_queue_patch_request"
        description: index to move the song to
      responses:
        "204":
          description: Success
      summary: set queue index
    post:
      description: Add a song to the queue
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_queue_post_request"
        description: video id of the song to add
      responses:
        "204":
          description: Success
      summary: add song to queue
  /api/v1/queue/{index}:
    delete:
      description: Remove a song from the queue
      parameters:
      - explode: false
        in: path
        name: index
        required: false
        schema:
          minimum: 0
          type: integer
          nullable: true
        style: simple
      responses:
        "204":
          description: Success
      summary: remove song from queue
    patch:
      description: Move a song in the queue
      parameters:
      - explode: false
        in: path
        name: index
        required: false
        schema:
          minimum: 0
          type: integer
          nullable: true
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_queue__index__patch_request"
        description: index to move the song to
      responses:
        "204":
          description: Success
      summary: move song in queue
  /api/v1/search:
    post:
      description: search for a song
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_v1_search_post_request"
        description: search query
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
          description: Success
      summary: search for a song
  /auth/{id}:
    post:
      description: ""
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_auth__id__post_200_response"
          description: Success
        "403":
          description: Forbidden
      security: []
      summary: ""
  /api/v1/ws:
    get:
      description: WebSocket endpoint for real-time updates
      responses:
        "101":
          description: Switching Protocols
      summary: websocket endpoint
components:
  parameters: {}
  schemas:
    _api_v1_like_state_get_200_response:
      example:
        state: DISLIKE
      properties:
        state:
          enum:
          - DISLIKE
          - INDIFFERENT
          - LIKE
          type: string
          nullable: true
      required:
      - state
    _api_v1_seek_to_post_request:
      properties:
        seconds:
          type: number
      required:
      - seconds
    _api_v1_shuffle_get_200_response:
      example:
        state: true
      properties:
        state:
          type: boolean
          nullable: true
      required:
      - state
    _api_v1_repeat_mode_get_200_response:
      example:
        mode: ONE
      properties:
        mode:
          enum:
          - ONE
          - NONE
          - ALL
          type: string
          nullable: true
      required:
      - mode
    _api_v1_switch_repeat_post_request:
      properties:
        iteration:
          type: number
      required:
      - iteration
    _api_v1_volume_get_200_response:
      example:
        state: 0.8008281904610115
        isMuted: true
      properties:
        state:
          type: number
        isMuted:
          type: boolean
      required:
      - isMuted
      - state
    _api_v1_volume_post_request:
      properties:
        volume:
          type: number
      required:
      - volume
    _api_v1_fullscreen_get_200_response:
      example:
        state: true
      properties:
        state:
          type: boolean
      required:
      - state
    _api_v1_song_info_get_200_response:
      example:
        playlistId: playlistId
        isPaused: true
        artist: artist
        songDuration: 6.027456183070403
        album: album
        imageSrc: imageSrc
        videoId: videoId
        mediaType: AUDIO
        title: title
        url: url
        uploadDate: uploadDate
        elapsedSeconds: 1.4658129805029452
        views: 0.8008281904610115
      properties:
        title:
          type: string
        artist:
          type: string
        views:
          type: number
        uploadDate:
          type: string
        imageSrc:
          type: string
          nullable: true
        isPaused:
          type: boolean
        songDuration:
          type: number
        elapsedSeconds:
          type: number
        url:
          type: string
        album:
          type: string
          nullable: true
        videoId:
          type: string
        playlistId:
          type: string
        mediaType:
          enum:
          - AUDIO
          - ORIGINAL_MUSIC_VIDEO
          - USER_GENERATED_CONTENT
          - PODCAST_EPISODE
          - OTHER_VIDEO
          type: string
      required:
      - artist
      - mediaType
      - songDuration
      - title
      - videoId
      - views
    _api_v1_queue_post_request:
      properties:
        videoId:
          type: string
        insertPosition:
          default: INSERT_AT_END
          enum:
          - INSERT_AT_END
          - INSERT_AFTER_CURRENT_VIDEO
          type: string
      required:
      - videoId
    _api_v1_queue_patch_request:
      properties:
        index:
          minimum: 0
          type: integer
      required:
      - index
    _api_v1_queue__index__patch_request:
      properties:
        toIndex:
          type: number
      required:
      - toIndex
    _api_v1_search_post_request:
      properties:
        query:
          type: string
        params:
          type: string
        continuation:
          type: string
      required:
      - query
    _auth__id__post_200_response:
      example:
        accessToken: accessToken
      properties:
        accessToken:
          type: string
      required:
      - accessToken
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
