name: Build nightly

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - run: |
        mkdir -p cmd/main/build
        go test ./...
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@e3914758a49697077f7bcd190d36582a61667aad
        with:
          bun-version-file: ".bun-version"
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Get bun cache dir
        id: bun-install-cache-dir
        run: echo "dir=$(bun pm cache)" >>"$GITHUB_OUTPUT"
      - name: Cache bun deps
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.bun-install-cache-dir.outputs.dir }}
          key: |
            ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
            ${{ runner.os }}-bun-
      - shell: bash
        run: |
          bun i --frozen-lockfile
          bun --workspaces run build
          rm -rf cmd/main/build
          mv control-panel/build cmd/main
          GIT_SHORT_TAG="v0.0.0+${{ github.sha }}" ./build_dist.sh
      - uses: actions/upload-artifact@v7
        with:
          name: pear-desktop-twitch-song-requests_windows_x64
          path: pear-desktop-twitch-song-requests_windows_x64.exe
          compression-level: 0
          if-no-files-found: error
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: pear-desktop-twitch-song-requests_windows_on_arm
          path: pear-desktop-twitch-song-requests_windows_on_arm.exe
          compression-level: 0
          if-no-files-found: error
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: pear-desktop-twitch-song-requests_macos_intel
          path: pear-desktop-twitch-song-requests_macos_intel
          compression-level: 0
          if-no-files-found: error
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: pear-desktop-twitch-song-requests_macos_apple_silicon
          path: pear-desktop-twitch-song-requests_macos_apple_silicon
          compression-level: 0
          if-no-files-found: error
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: pear-desktop-twitch-song-requests_linux_amd64
          path: pear-desktop-twitch-song-requests_linux_amd64
          compression-level: 0
          if-no-files-found: error
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: pear-desktop-twitch-song-requests_linux_arm64
          path: pear-desktop-twitch-song-requests_linux_arm64
          compression-level: 0
          if-no-files-found: error
          archive: false
