name: Release

on:
  push:
    branches: [master]
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-web:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.version-tag-ref.outputs.ref }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1.1.2
        with:
          node-version-file: ".node-version"
          cache: true
          run-install: true
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - id: version-tag-ref
        run: |
          if [[ '${{ github.ref_type }}' = 'tag' ]]; then
            ref='${{ github.ref }}'
            echo "ref=${ref#refs/tags/}" >>"$GITHUB_OUTPUT"
            go run -ldflags="-X main.version=${ref#refs/tags/}" ./cmd/validate_semver
          else
            echo "ref=v0.0.0+${{ github.sha }}" >>"$GITHUB_OUTPUT"
          fi
      - shell: bash
        run: vp run build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: web-assets
          path: control-panel/build
          if-no-files-found: error

  build-go:
    needs: build-web
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            runner: ubuntu-latest
            artifact_name: pear-desktop-twitch-song-requests_linux_amd64
            exec_name: pear-desktop-twitch-song-requests_linux_amd64
          - goos: linux
            goarch: arm64
            runner: ubuntu-24.04-arm
            artifact_name: pear-desktop-twitch-song-requests_linux_arm64
            exec_name: pear-desktop-twitch-song-requests_linux_arm64
          - goos: windows
            goarch: amd64
            runner: ubuntu-latest
            artifact_name: pear-desktop-twitch-song-requests_windows_x64
            exec_name: pear-desktop-twitch-song-requests_windows_x64.exe
          - goos: windows
            goarch: arm64
            runner: ubuntu-24.04-arm
            artifact_name: pear-desktop-twitch-song-requests_windows_on_arm
            exec_name: pear-desktop-twitch-song-requests_windows_on_arm.exe
          - goos: darwin
            goarch: amd64
            runner: ubuntu-latest
            artifact_name: pear-desktop-twitch-song-requests_macos_intel
            exec_name: pear-desktop-twitch-song-requests_macos_intel
          - goos: darwin
            goarch: arm64
            runner: ubuntu-24.04-arm
            artifact_name: pear-desktop-twitch-song-requests_macos_apple_silicon
            exec_name: pear-desktop-twitch-song-requests_macos_apple_silicon
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: web-assets
          path: cmd/main/build
      - shell: bash
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -ldflags="-s -w -X main.version=${{ needs.build-web.outputs.ref }}" \
            -trimpath -o "${{ matrix.exec_name }}" ./cmd/main
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.exec_name }}
          compression-level: 0
          if-no-files-found: error
          archive: false

  publish:
    needs: [build-web, build-go]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: pear-desktop-twitch-song-requests_*
          merge-multiple: true
      - uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ needs.build-web.outputs.ref }}
          prerelease: ${{ contains(github.ref, '-rc') }}
          make_latest: true
          generate_release_notes: true
          preserve_order: true
          fail_on_unmatched_files: true
          files: |
            pear-desktop-twitch-song-requests_windows_x64.exe
            pear-desktop-twitch-song-requests_windows_on_arm.exe
            pear-desktop-twitch-song-requests_linux_amd64
            pear-desktop-twitch-song-requests_linux_arm64
            pear-desktop-twitch-song-requests_macos_intel
            pear-desktop-twitch-song-requests_macos_apple_silicon
