// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteQueueItem(arg1) {
  return window['go']['main']['App']['DeleteQueueItem'](arg1);
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetRequestersHistory(arg1, arg2) {
  return window['go']['main']['App']['GetRequestersHistory'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTwitchCustomRewards() {
  return window['go']['main']['App']['GetTwitchCustomRewards']();
}

export function GetTwitchInfo() {
  return window['go']['main']['App']['GetTwitchInfo']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetSubscriptionHandlers() {
  return window['go']['main']['App']['SetSubscriptionHandlers']();
}

export function SetSubscriptionHandlersBot() {
  return window['go']['main']['App']['SetSubscriptionHandlersBot']();
}
