// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteQueueItem(arg1:number):Promise<void>;

export function GetQueue():Promise<Array<main.SongQueueItem>>;

export function GetRequestersHistory(arg1:number,arg2:number):Promise<main.HistoryResponse>;

export function GetSettings():Promise<main.SettingsResponse>;

export function GetTwitchCustomRewards():Promise<Array<main.SelectableReward>>;

export function GetTwitchInfo():Promise<main.TwitchInfoPayload>;

export function Login(arg1:boolean):Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function SetSubscriptionHandlers():Promise<void>;

export function SetSubscriptionHandlersBot():Promise<void>;
